### ISSUE TITLE
Citi Bike Website Error

### ISSUE THREAD

**Issue by rgardner** [rgardner/citi-bike-notifier#6]
Net::HTTPGatewayTimeOut
<pre>
/home/bob/.rvm/gems/ruby-2.0.0-p451@citi-bike-notifier/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:308:in `fetch': 504 => Net::HTTPGatewayTimeOut for https://citibikenyc.com/member/trips -- unhandled response (Mechanize::ResponseCodeError)
	from /home/bob/.rvm/gems/ruby-2.0.0-p451@citi-bike-notifier/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:976:in `response_redirect'
	from /home/bob/.rvm/gems/ruby-2.0.0-p451@citi-bike-notifier/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:300:in `fetch'
	from /home/bob/.rvm/gems/ruby-2.0.0-p451@citi-bike-notifier/gems/mechanize-2.7.3/lib/mechanize.rb:1281:in `post_form'
	from /home/bob/.rvm/gems/ruby-2.0.0-p451@citi-bike-notifier/gems/mechanize-2.7.3/lib/mechanize.rb:548:in `submit'
	from /home/bob/.rvm/gems/ruby-2.0.0-p451@citi-bike-notifier/gems/mechanize-2.7.3/lib/mechanize/form.rb:223:in `submit'
	from /home/bob/citi-bike-notifier/citi_scraper.rb:36:in `login'
	from /home/bob/citi-bike-notifier/citi_scraper.rb:50:in `trips'
	from driver.rb:40:in `block in <main>'
	from driver.rb:38:in `loop'
	from driver.rb:38:in `<main>'
</pre>

**Comment by rgardner** [comment]
This looks like simply a problem on Citi Bike's end.
